### ISSUE TITLE
Building tun/tap kernel driver

### ISSUE THREAD

**Issue by ZigFisher** [Dafang-Hacks/kernel#1]
Good afternoon !
Please tell me how I can build a tun/tap driver (tun.ko) for this kernel.
Thank you !

**Comment by nik0** [comment]
You can follow (the long, sorry) thread here
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/236

**Comment by EliasKotlyar** [comment]
Tun/Tap Driver is already included in the new kernel. So i am closing this issue.

**Comment by ZigFisher** [comment]
TNX, Sir !
